FROM alpine:3.19

EXPOSE 8080

RUN echo "http://openresty.org/package/alpine/v3.15/main" >> /etc/apk/repositories \
	&& wget 'http://openresty.org/package/admin@openresty.com-5ea678a6.rsa.pub' -O /etc/apk/keys/admin@openresty.com-5ea678a6.rsa.pub \
	&& apk add --no-cache luarocks5.1 lua-inspect lua5.1-sql-mysql openresty gcc musl-dev openssl-dev lua5.1-dev \
	&& luarocks-5.1 install lapis \
	&& luarocks-5.1 install lua-resty-rsa \
	&& mkdir /usr/local/openresty/nginx/client_body_temp \
	&& adduser -h /opt/app -D -H openresty \
	&& chown -R openresty:root /usr/local/openresty/nginx/ \
	&& chmod -R g=u /usr/local/openresty/nginx

COPY container/nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY . /opt/app

WORKDIR /opt/app

USER 1000

CMD /usr/local/openresty/nginx/sbin/nginx -g 'daemon off; master_process on;'
