# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.box = 'debian/bookworm64'
  config.vm.box_check_update = false

  config.vm.hostname = "debian.lua.local"
  config.vm.network 'private_network', ip: "192.168.56.100"
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 512
    vb.cpus = 1
  end
  config.vm.provider 'libvirt' do |lv|
    lv.memory = 512
    lv.cpus = 1
    lv.cputopology :sockets => 1, :cores => 1, :threads => '1'
  end
  config.vm.provision 'shell', path: 'provision.sh'
end
